// WCAG AA text contrast for themes generated by Theme from Image (#791).
//
// The built-in themes are covered by tests/themes/theme-token-contrast.test.ts.
// Generated themes depend on an arbitrary image palette, so this checks the
// CSS buildTheme() emits over many seeded palettes. Surfaces are composited
// from the emitted tokens exactly as the browser paints them, and contrast is
// computed with an oracle independent of the production helper.
import { describe, expect, it } from "vitest";
import { buildTheme, contrastRatio, hexToRgb, rgbToOklch } from "$lib/domain/theme-from-palette";

const AA_TEXT = 4.5;
const FILL_TOKENS = ["accent", "system-success", "system-caution", "system-critical"] as const;
const TEXT_TOKENS = ["text-primary", "text-secondary", "text-tertiary"] as const;
/** Accent tint behind selected rows / active items (components use 8–20%). */
const SELECTED_ALPHA = 0.2;

type Rgb = readonly [number, number, number];
type Rgba = readonly [number, number, number, number];

function parseColor(value: string): Rgba {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1];
  }
  const rgba = /^rgba\((\d+), (\d+), (\d+), ([\d.]+)\)$/.exec(value);
  if (rgba) return [+rgba[1], +rgba[2], +rgba[3], +rgba[4]];
  throw new Error(`unparseable colour ${value}`);
}

/** Source-over composite, rounded to 8-bit like a rendered pixel. */
function over([r, g, b, a]: Rgba, under: Rgb): Rgb {
  const c = (top: number, bottom: number) => Math.round(top * a + bottom * (1 - a));
  return [c(r, under[0]), c(g, under[1]), c(b, under[2])];
}

function oracleContrast(a: Rgb, b: Rgb): number {
  const lum = ([r, g, bl]: Rgb) => {
    const ch = (v: number) => {
      const s = v / 255;
      return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
    };
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(bl);
  };
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

function tokensOf(css: string): Map<string, string> {
  return new Map([...css.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)].map((m) => [m[1], m[2].trim()]));
}

function opaque(tokens: Map<string, string>, name: string): Rgb {
  const value = tokens.get(name);
  if (value === undefined) throw new Error(`--${name} missing`);
  const [r, g, b, a] = parseColor(value);
  if (a !== 1) throw new Error(`--${name} must be opaque, got ${value}`);
  return [r, g, b];
}

/** Every surface text can sit on, composited from the emitted tokens. */
function surfaces(tokens: Map<string, string>): Record<string, Rgb> {
  const solid = opaque(tokens, "background-solid");
  const card = over(parseColor(tokens.get("background-card")!), solid);
  const hover = parseColor(tokens.get("subtle-fill-secondary")!);
  const [ar, ag, ab] = parseColor(tokens.get("accent")!);
  return {
    solid,
    card,
    "card-secondary": over(parseColor(tokens.get("background-card-secondary")!), solid),
    miller: opaque(tokens, "miller-bg"),
    hover: over(hover, solid),
    "hover-on-card": over(hover, card),
    selected: over([ar, ag, ab, SELECTED_ALPHA], solid),
  };
}

function worstContrast(text: Rgb, surf: Record<string, Rgb>): number {
  return Math.min(...Object.values(surf).map((s) => oracleContrast(text, s)));
}

const oklchOf = (c: Rgb) => rgbToOklch({ r: c[0], g: c[1], b: c[2] });
const hueDrift = (a: number, b: number) => Math.abs(((b - a + 540) % 360) - 180);

/** Largest chroma at OKLCH lightness `l` and hue `h` inside sRGB (Ottosson's inverse). */
function maxInGamutChroma(l: number, h: number): number {
  const inGamut = (c: number) => {
    const A = c * Math.cos((h * Math.PI) / 180);
    const B = c * Math.sin((h * Math.PI) / 180);
    const L = (l + 0.3963377774 * A + 0.2158037573 * B) ** 3;
    const M = (l - 0.1055613458 * A - 0.0638541728 * B) ** 3;
    const S = (l - 0.0894841775 * A - 1.291485548 * B) ** 3;
    return [
      4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S,
      -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S,
      -0.0041960863 * L - 0.7034186147 * M + 1.707614701 * S,
    ].every((v) => v >= -1e-4 && v <= 1 + 1e-4);
  };
  let [lo, hi] = [0, 0.5];
  for (let i = 0; i < 30; i++) {
    const mid = (lo + hi) / 2;
    if (inGamut(mid)) lo = mid; else hi = mid;
  }
  return lo;
}

/** Deterministic PRNG so failures reproduce. */
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const hex = (r: number, g: number, b: number) =>
  "#" + [r, g, b].map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, "0")).join("");

function palettes(): Array<{ family: string; colors: string[] }> {
  const rand = mulberry32(791);
  const byte = (lo = 0, hi = 255) => lo + Math.floor(rand() * (hi - lo + 1));
  const any = () => hex(byte(), byte(), byte());
  const out: Array<{ family: string; colors: string[] }> = [];
  for (let i = 0; i < 60; i++) {
    out.push({ family: "dark", colors: [hex(byte(0, 90), byte(0, 90), byte(0, 90)), any(), any(), any()] });
    out.push({ family: "light", colors: [hex(byte(170), byte(170), byte(170)), any(), any(), any()] });
    const g = () => { const v = byte(); return hex(v, v, v); };
    out.push({ family: "grey-only", colors: [g(), g(), g()] });
    out.push({ family: "single-colour", colors: [any()] });
    const m = () => { const v = byte(150, 185); return hex(v + byte(-6, 6), v + byte(-6, 6), v + byte(-6, 6)); };
    out.push({ family: "near-mid-grey", colors: [m(), m(), any()] });
  }
  // Hand-picked palettes that defeat fixed interpolation: pale accents on
  // light surfaces, bright surfaces just under the dark/light threshold.
  for (const colors of [
    ["#aaaaaa", "#ffffff", "#ffff00"],
    ["#a9a9a9", "#f0f0f0"],
    ["#b4b4b4", "#ffe066", "#a0ffa0"],
    ["#f2ead9", "#ffd6e0", "#c8b89a"],
    ["#ffffff"],
    ["#000000"],
    ["#808080"],
    ["#101418", "#1a1d22", "#22262c"],
    ["#00ff00", "#ff00ff", "#00ffff"],
  ]) out.push({ family: "regression", colors });
  return out;
}

const cases = palettes().map((p, i) => {
  const theme = buildTheme(p.colors, `img-${i}`, `P${i}`);
  if (!theme) throw new Error(`no theme for ${p.colors.join(",")}`);
  const tokens = tokensOf(theme.css);
  return { ...p, label: `${p.family} ${p.colors.join(" ")}`, tokens, surf: surfaces(tokens) };
});

describe("generated theme text contrast", () => {
  it("covers every palette family", () => {
    const families = new Set(cases.map((c) => c.family));
    expect([...families].sort()).toEqual(
      ["dark", "grey-only", "light", "near-mid-grey", "regression", "single-colour"],
    );
  });

  it("every text token meets AA on every surface", () => {
    const failures = cases.flatMap(({ label, tokens, surf }) =>
      TEXT_TOKENS.flatMap((token) => {
        const ratio = worstContrast(opaque(tokens, token), surf);
        return ratio >= AA_TEXT ? [] : [`${label}: --${token} ${ratio.toFixed(2)}`];
      }),
    );
    expect(failures).toEqual([]);
  });

  it("text drawn in a fill colour meets AA on every surface", () => {
    const failures = cases.flatMap(({ label, tokens, surf }) =>
      FILL_TOKENS.flatMap((fill) => {
        const token = tokens.has(`${fill}-text`) ? `${fill}-text` : fill;
        const ratio = worstContrast(opaque(tokens, token), surf);
        return ratio >= AA_TEXT ? [] : [`${label}: --${token} ${ratio.toFixed(2)}`];
      }),
    );
    expect(failures).toEqual([]);
  });

  it("emits a -text companion only for a fill that is not legible as text", () => {
    const failures = cases.flatMap(({ label, tokens, surf }) =>
      FILL_TOKENS.flatMap((fill) => {
        if (!tokens.has(`${fill}-text`)) return [];
        const ratio = worstContrast(opaque(tokens, fill), surf);
        return ratio < 4.6 ? [] : [`${label}: --${fill}-text emitted although --${fill} is ${ratio.toFixed(2)}`];
      }),
    );
    expect(failures).toEqual([]);
  });

  it("keeps primary > secondary > tertiary with secondary ≥ 1.2× tertiary", () => {
    const failures = cases.flatMap(({ label, tokens, surf }) => {
      const [p, s, t] = TEXT_TOKENS.map((token) => worstContrast(opaque(tokens, token), surf));
      return p > s && s > t && s >= 1.2 * t ? [] : [`${label}: ${p.toFixed(2)} / ${s.toFixed(2)} / ${t.toFixed(2)}`];
    });
    expect(failures).toEqual([]);
  });

  it("solves -text companions in OKLCH lightness, keeping the fill's hue and chroma", () => {
    const failures = cases.flatMap(({ label, tokens }) =>
      FILL_TOKENS.flatMap((fill) => {
        if (!tokens.has(`${fill}-text`)) return [];
        const [from, to] = [oklchOf(opaque(tokens, fill)), oklchOf(opaque(tokens, `${fill}-text`))];
        if (from.c < 0.03) return []; // a near-grey fill has no hue to keep
        // Chroma may only shrink as far as the sRGB gamut forces at the new lightness.
        const expected = Math.min(from.c, maxInGamutChroma(to.l, from.h));
        const drift = hueDrift(from.h, to.h);
        return to.c >= expected - 0.02 && (expected < 0.03 || drift <= 4)
          ? []
          : [`${label}: --${fill}-text c ${to.c.toFixed(3)} (expected ≥ ${expected.toFixed(3)}), hue drift ${drift.toFixed(1)}°`];
      }),
    );
    expect(failures).toEqual([]);
  });

  it("keeps the surface's tint in secondary and tertiary text", () => {
    // Text is seeded from the surface hue; solving lightness must not grey it.
    // (Primary text sits near white/black by design, where hue is noise.)
    const failures = cases.flatMap(({ label, tokens }) => {
      const bg = oklchOf(opaque(tokens, "background-solid"));
      if (bg.c < 0.03) return [];
      return (["text-secondary", "text-tertiary"] as const).flatMap((token) => {
        const t = oklchOf(opaque(tokens, token));
        const drift = hueDrift(bg.h, t.h);
        return t.c >= 0.2 * bg.c && drift <= 25
          ? []
          : [`${label}: --${token} c ${t.c.toFixed(3)} vs surface ${bg.c.toFixed(3)}, hue drift ${drift.toFixed(1)}°`];
      });
    });
    expect(failures).toEqual([]);
  });

  it("fixes the light pale-accent palette from the issue with darker -text variants", () => {
    const { tokens } = cases.find((c) => c.colors.join() === "#f2ead9,#ffd6e0,#c8b89a")!;
    // The status fills are the stock bright colours, illegible on a light surface.
    expect(tokens.has("system-caution-text")).toBe(true);
    expect(tokens.has("system-critical-text")).toBe(true);
  });
});

describe("contrastRatio", () => {
  const rgb = (h: string) => hexToRgb(h)!;
  it("matches the WCAG reference ratios", () => {
    expect(contrastRatio(rgb("#000000"), rgb("#ffffff"))).toBeCloseTo(21, 5);
    expect(contrastRatio(rgb("#ffffff"), rgb("#000000"))).toBeCloseTo(21, 5);
    expect(contrastRatio(rgb("#777777"), rgb("#ffffff"))).toBeCloseTo(4.48, 2);
    expect(contrastRatio(rgb("#abcdef"), rgb("#abcdef"))).toBe(1);
  });
});

describe("malformed palettes", () => {
  it("returns no theme when no entry is a valid hex colour", () => {
    for (const colors of [[], [""], ["#"], ["#12"], ["#12345"], ["#1234567"], ["red"], ["rgba(0,0,0,1)"], ["#gggggg"]]) {
      expect(buildTheme(colors, "img-m", "M")).toBeNull();
    }
  });

  it("ignores malformed entries mixed with valid ones and still meets AA", () => {
    const theme = buildTheme(["zzz", "#a9a9a9", "#12", "#ffffff"], "img-m", "M")!;
    expect(theme).not.toBeNull();
    const tokens = tokensOf(theme.css);
    const surf = surfaces(tokens);
    for (const token of TEXT_TOKENS) {
      expect(worstContrast(opaque(tokens, token), surf)).toBeGreaterThanOrEqual(AA_TEXT);
    }
  });
});
