/**
 * Theme generation from an extracted image palette (#203).
 * Pure functions: palette colors in, complete theme CSS out — everything the
 * theme engine's discovery scan needs (--theme-name, --background-solid,
 * --divider, --accent) plus the full variable set the UI consumes.
 */

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

export function hexToRgb(hex: string): Rgb | null {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return { r: (n >> 16) & 0xff, g: (n >> 8) & 0xff, b: n & 0xff };
}

export function rgbToHex({ r, g, b }: Rgb): string {
  const c = (v: number) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, "0");
  return `#${c(r)}${c(g)}${c(b)}`;
}

/** WCAG-ish relative luminance, 0 (black) … 1 (white). */
export function luminance({ r, g, b }: Rgb): number {
  const lin = (v: number) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/** Saturation in [0,1] (HSL definition). */
export function saturation({ r, g, b }: Rgb): number {
  const max = Math.max(r, g, b) / 255;
  const min = Math.min(r, g, b) / 255;
  if (max === min) return 0;
  const l = (max + min) / 2;
  const d = max - min;
  return l > 0.5 ? d / (2 - max - min) : d / (max + min);
}

/** Mix `a` toward `b` by t∈[0,1]. */
export function mix(a: Rgb, b: Rgb, t: number): Rgb {
  return {
    r: a.r + (b.r - a.r) * t,
    g: a.g + (b.g - a.g) * t,
    b: a.b + (b.b - a.b) * t,
  };
}

const BLACK: Rgb = { r: 8, g: 9, b: 12 };
const WHITE: Rgb = { r: 248, g: 249, b: 252 };

function rgba({ r, g, b }: Rgb, a: number): string {
  return `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, ${a})`;
}

/** A filesystem- and CSS-safe theme id from an arbitrary image name. */
export function themeIdFromName(imageName: string): string {
  const base = imageName.replace(/\.[^.]+$/, "").toLowerCase()
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
  return `img-${base || "theme"}`;
}

export interface GeneratedTheme {
  id: string;
  name: string;
  css: string;
  /** True when the generated theme is dark (drives color-scheme). */
  dark: boolean;
}

/**
 * Build a complete theme from dominant colors (dominant first).
 * The most dominant color decides light/dark; the most saturated
 * sufficiently-contrasting color becomes the accent.
 */
export function buildTheme(hexColors: string[], id: string, name: string): GeneratedTheme | null {
  const colors = hexColors.map(hexToRgb).filter((c): c is Rgb => c !== null);
  if (colors.length === 0) return null;

  const dominant = colors[0];
  const dark = luminance(dominant) < 0.4;

  // Surface: dominant pulled toward the extreme so text always has room.
  const bg = dark ? mix(dominant, BLACK, 0.72) : mix(dominant, WHITE, 0.78);
  const bgLum = luminance(bg);

  // Accent: most saturated palette color that isn't the surface itself.
  const accent = [...colors]
    .sort((a, b) => saturation(b) - saturation(a))
    .find((c) => Math.abs(luminance(c) - bgLum) > 0.08) ?? mix(dominant, dark ? WHITE : BLACK, 0.5);
  // Keep the accent legible against the surface.
  const accentAdj = dark
    ? (luminance(accent) < 0.18 ? mix(accent, WHITE, 0.35) : accent)
    : (luminance(accent) > 0.6 ? mix(accent, BLACK, 0.35) : accent);

  const text = dark ? mix(WHITE, bg, 0.06) : mix(BLACK, bg, 0.08);
  const textDim = mix(text, bg, 0.42);
  const textFaint = mix(text, bg, 0.68);
  const raise = (t: number) => rgbToHex(mix(bg, dark ? WHITE : BLACK, t));
  const onAccent = luminance(accentAdj) > 0.45 ? rgbToHex(BLACK) : rgbToHex(WHITE);

  const css = `/* Generated by Theme from Image — source: ${name} */
[data-theme="${id}"] {
  color-scheme: ${dark ? "dark" : "light"};

  --theme-name: "${name}";
  --theme-description: "Generated from an image";

  --accent: ${rgbToHex(accentAdj)};
  --accent-light: ${rgbToHex(mix(accentAdj, WHITE, 0.25))};
  --accent-dark: ${rgbToHex(mix(accentAdj, BLACK, 0.25))};
  --text-primary: ${rgbToHex(text)};
  --text-secondary: ${rgbToHex(textDim)};
  --text-tertiary: ${rgbToHex(textFaint)};
  --text-on-accent: ${onAccent};

  --background-solid: ${rgbToHex(bg)};
  --background-mica: ${rgba(bg, 0.86)};
  --background-acrylic: ${rgba(mix(bg, dark ? WHITE : BLACK, 0.04), 0.8)};
  --background-card: ${rgba(mix(bg, dark ? WHITE : BLACK, 0.09), 0.45)};
  --background-card-secondary: ${rgba(mix(bg, dark ? WHITE : BLACK, 0.05), 0.4)};
  --miller-bg: ${raise(0.03)};
  --content-bg: ${rgba(bg, 0.35)};

  --surface-stroke: ${rgba(text, 0.09)};
  --surface-stroke-flyout: ${rgba(text, 0.14)};
  --divider: ${rgba(text, 0.1)};

  --control-fill: ${rgba(text, 0.055)};
  --control-fill-secondary: ${rgba(text, 0.085)};
  --control-fill-tertiary: ${rgba(text, 0.03)};
  --control-fill-disabled: ${rgba(text, 0.02)};
  --subtle-fill: transparent;
  --subtle-fill-secondary: ${rgba(text, 0.055)};
  --subtle-fill-tertiary: ${rgba(text, 0.03)};
  --control-stroke: ${rgba(text, 0.14)};
  --control-stroke-secondary: ${rgba(text, 0.08)};

  --address-bar-bg: ${rgba(mix(bg, dark ? WHITE : BLACK, 0.05), 0.6)};
  --address-bar-stroke: ${rgba(text, 0.1)};
  --address-bar-highlight: ${rgba(accentAdj, 0.4)};
  --address-bar-bg-hover: ${rgba(mix(bg, dark ? WHITE : BLACK, 0.08), 0.7)};
  --address-bar-stroke-hover: ${rgba(text, 0.16)};

  --focus-stroke-outer: ${rgbToHex(accentAdj)};
  --focus-stroke-inner: ${rgba(bg, 1)};

  --system-critical: #ef5350;
  --system-success: #66bb6a;
  --system-caution: #ffa726;

  --shadow-flyout: 0 8px 16px ${rgba(BLACK, dark ? 0.5 : 0.14)};
  --shadow-dialog: 0 32px 64px ${rgba(BLACK, dark ? 0.6 : 0.18)};
  --shadow-tooltip: 0 4px 8px ${rgba(BLACK, dark ? 0.4 : 0.12)};
  --shadow-card: 0 2px 4px ${rgba(BLACK, dark ? 0.26 : 0.06)};
  --shadow-subtle: 0 1px 2px ${rgba(BLACK, dark ? 0.2 : 0.05)};
  --mica-overlay: ${rgba(bg, 0.5)};

  --sidebar-opacity: 1;
  --toolbar-opacity: 1;
  --content-opacity: 1;
  --titlebar-opacity: 1;
  --statusbar-opacity: 1;
}
`;
  return { id, name, css, dark };
}
